export const DEFAULT_DAILY_SCENE = {
    ANYTIME: 'ANYTIME',
    WAKE_UP: 'WAKE_UP',
    MORNING: 'MORNING',
    NOON: 'NOON',
    AFTERNOON: 'AFTERNOON',
    EVENING: 'EVENING',
    BEFORE_SLEEP: 'BEFORE_SLEEP'
}
